# Generated by Django 5.2.6 on 2025-09-14 18:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userresponse',
            unique_together={('user', 'poll', 'question')},
        ),
        migrations.AddField(
            model_name='userresponse',
            name='anonymous_user_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userresponse',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='userresponse',
            unique_together={('anonymous_user_id', 'poll', 'question'), ('user', 'poll', 'question')},
        ),
    ]
